// Copyright 2017 Tunnler Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.
//

#pragma once

#include <atomic>
#include <deque>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <thread>

#include "tunnler/room.h"
#include "tunnler/tunnler.h"

// This is what a client [person joining a server] would use.
// It also has to be used if you host a game yourself (You'd create both, a Room and a RoomMembership for yourself)
class RoomMember final {
public:

    // Different types for callbacks
    enum class EventType {
        OnFramesReceived,
        OnMessagesReceived,
        OnRoomChanged,
        OnStateChanged,
    };

    // The handle for the callback functions
    struct Connection {
        EventType event_type;
        std::shared_ptr<std::function<void()> > callback;
    };

    struct MemberInformation {
        std::string nickname;      // Nickname of the member.
        std::string game_name;     // Name of the game they're currently playing, or empty if they're not playing anything.
        MacAddress mac_address;    // MAC address associated with this member.
    };

    enum class State {
        Idle,     // Default state
        Error,    // Some error [permissions to network device missing or something]
        Joining,  // The client is attempting to join a room.
        Joined,   // The client is connected to the room and is ready to send/receive packets.

        // Reasons for connection loss
        LostConnection,

        // Reasons why connection was rejected
        RoomFull,        // The room is full and is not accepting any more connections.
        RoomDestroyed,   // Unknown reason, server not reachable or not responding for w/e reason
        NameCollision,   // Somebody is already using this name
        MacCollision,    // Somebody is already using that mac-address
        WrongVersion,    // The RakNet version does not match.
    };

    /// Represents a chat message.
    struct ChatEntry {
        std::string nickname;    ///< Nickname of the client who sent this message.
        std::string message;     ///< Body of the message.
    };

    using MemberList = std::vector<MemberInformation>;

    RoomMember();
    ~RoomMember();

    /**
     * Returns the status of our connection to the room.
     */
    State GetState() const { return state; };

    /**
     * Returns whether we're connected to a server or not.
     */
    bool IsConnected() const;

    /**
     * Returns to nickname of the member.
     */
    const std::string& GetNickname() const { return nickname; }

    /**
     * Returns the mac address of the member.
     */
    const MacAddress& GetMacAddress() const { return mac_address; }

    /**
     * Returns information about the members in the room we're currently connected to.
     */
    const MemberList& GetMemberInformation() const { return member_information; }

    /**
     * Returns information about the room we're currently connected to.
     */
    RoomInformation GetRoomInformation() const { return room_information; };

    /**
     * Returns a list of received chat messages since the last call.
     */
    std::deque<ChatEntry> PopChatEntries();

    /**
     * Returns a list of received 802.11 frames from the specified sender
     * matching the type since the last call.
     */
    std::deque<WifiPacket> PopWifiPackets(WifiPacket::PacketType type, const MacAddress& sender = NoPreferredMac);

    /**
     * Sends a chat message to the room.
     * @param message The contents of the message.
     */
    void SendChatMessage(const std::string& message);

	/**
     * Sends a WiFi packet to the room.
     * @param packet The WiFi packet to send.
     */
    void SendWifiPacket(const WifiPacket& packet);

    /**
     * Returns a string with informations about the connection
     */
    std::string GetStatistics() const;

    /**
     * Returns the latest ping to the room
	 */
    int GetPing() const;

    /**
     * Registers a callback functions to the room member
     * @param callback The function to call
     * @param event_type The event on which callback will be called
     * \return a connection handle
     */
    Connection Connect(std::function<void()> callback, EventType event_type);

    /**
     * Deregisters a callback function
     * @param connection The connection handle generated by Connect()
     */
    void Disconnect(Connection connection);

    /**
     * Attempts to join a room at the specified address and port, using the specified nickname.
     * This may fail if the username is already taken.
     */
    void Join(const std::string& nickname, const std::string& server = "127.0.0.1",
              const uint16_t serverPort = DefaultRoomPort, const uint16_t clientPort = 0);

    /**
     * Leaves the current room.
     */
    void Leave();

private:
    std::atomic<State> state{State::Idle}; ///< Current state of the RoomMember.
    using CallbackSet = std::set<std::shared_ptr<std::function<void()>> >;
    std::map<EventType, CallbackSet> callback_map;
    std::mutex callback_mutex;  //< The mutex used for handling callbacks
    
    MemberList member_information; ///< Information about the clients connected to the same room as us.
    RoomInformation room_information; ///< Information about the room we're connected to.

    RakNet::RakPeerInterface* peer; ///< RakNet network interface.

    std::string nickname; ///< The nickname of this member.
    MacAddress mac_address; ///< The mac_address of this member.

    /**
     * Extracts a chat entry from a received RakNet packet and adds it to the chat queue.
     * @param packet The RakNet packet that was received.
     */
    void HandleChatPacket(const RakNet::Packet* packet);

    /**
     * Extracts a WifiPacket from a received RakNet packet and adds it to the proper queue.
     * @param packet The RakNet packet that was received.
     */
    void HandleWifiPackets(const RakNet::Packet* packet);

    /**
     * Extracts RoomInformation and MemberInformation from a received RakNet packet.
     * @param packet The RakNet packet that was received.
     */
    void HandleRoomInformationPacket(const RakNet::Packet* packet);

    /**
     * Extracts a MAC Address from a received RakNet packet.
     * @param packet The RakNet packet that was received.
     */
    void HandleJoinPacket(const RakNet::Packet* packet);

    /**
     * Calls all registered callback function, registered with event_type.
     */
    void Invoke(const EventType event_type);

    std::unique_ptr<std::thread> receive_thread; ///< Thread that receives and dispatches network packets

    /// Max size of the data queue before the oldest entry is expunged.
    /// TODO(Ben): Find a good value for this
    static const size_t MaxDataQueueSize = 3;

    /// Max size of the beacon queue before the oldest entry is expunged.
    /// This number was empirically calculated, keeping too many frames will
    // cause an overflow in UDS::RecvBeaconBroadcastData.
    static const size_t MaxBeaconQueueSize = 25;

    /// Max size of the beacon queue before the oldest entry is expunged.
    /// This number was empirically calculated, keeping too many frames will
    // cause an overflow in UDS::RecvBeaconBroadcastData.
    static const size_t MaxManagementQueueSize = 25;

    std::mutex chat_mutex;             ///< Mutex to protect access to the chat queue.
    std::deque<ChatEntry> chat_queue;    ///< List of all chat messages received since last PopChatEntries was called
    std::mutex data_mutex;             ///< Mutex to protect access to the data queue.
    std::deque<WifiPacket> data_queue;   ///< List of all received 802.11 frames with type `Data`
    std::mutex beacon_mutex;             ///< Mutex to protect access to the beacons queue.
    std::deque<WifiPacket> beacon_queue; ///< List of all received 802.11 frames with type `Beacon`
    std::mutex management_mutex;             ///< Mutex to protect access to the management queue.
    std::deque<WifiPacket> management_queue; ///< List of all received 802.11 frames with type `Management`

    RakNet::SystemAddress server_address; ///< Address of the server we're connected to.

    std::mutex network_mutex; ///< Mutex that controls access to the `peer` variable.

    /// Thread function that will receive and dispatch messages until connection is lost.
    void ReceiveLoop();
};
